import { BONER_ADDRESS } from "../signals/config.js";
import type { BacktestCase } from "../signals/types.js";

/**
 * BONER squeeze timeline — reconstructed from on-chain + DexScreener case study.
 * Used to validate signal rules fire BEFORE the Aug 30–31 weekend pump.
 *
 * Sources: launch Aug 20, first vol spike Aug 28, squeeze peak Aug 30–31.
 */
export const BONER_BACKTEST_CASES: BacktestCase[] = [
  {
    id: "boner-d1",
    label: "Day 1 post-launch",
    date: "2026-08-21",
    description: "Fresh launch, low activity — should stay quiet.",
    minLevel: "none",
    maxLevel: "watch",
    input: {
      address: BONER_ADDRESS,
      symbol: "BONER",
      name: "Boner Coin",
      primaryPair: "BONER/HIMS",
      quoteSymbol: "HIMS",
      isStockPaired: true,
      volume24hUsd: 45_000,
      liquidityUsd: 180_000,
      fdvUsd: 2_000_000,
      priceChange24h: 5,
      quoteLockRatio: 0.08,
      volumeSpikeRatio: 1.2,
      daysSinceLaunch: 1,
      launchAt: "2026-08-20T20:59:46.000Z",
      longUrl: `https://app.long.xyz/tokens/${BONER_ADDRESS}`,
    },
  },
  {
    id: "boner-d5",
    label: "Mid flat period",
    date: "2026-08-25",
    description: "Still flat, lock building slowly — watch at most.",
    minLevel: "none",
    maxLevel: "watch",
    input: {
      address: BONER_ADDRESS,
      symbol: "BONER",
      primaryPair: "BONER/HIMS",
      quoteSymbol: "HIMS",
      isStockPaired: true,
      volume24hUsd: 80_000,
      liquidityUsd: 400_000,
      fdvUsd: 8_000_000,
      priceChange24h: 3,
      quoteLockRatio: 0.18,
      volumeSpikeRatio: 1.5,
      daysSinceLaunch: 5,
      launchAt: "2026-08-20T20:59:46.000Z",
      longUrl: `https://app.long.xyz/tokens/${BONER_ADDRESS}`,
    },
  },
  {
    id: "boner-d8-spike",
    label: "First volume spike (trigger day)",
    date: "2026-08-28",
    description:
      "Aug 28 volume breakout — MUST alert before weekend pump. This is the key backtest.",
    minLevel: "alert",
    input: {
      address: BONER_ADDRESS,
      symbol: "BONER",
      primaryPair: "BONER/HIMS",
      quoteSymbol: "HIMS",
      isStockPaired: true,
      volume24hUsd: 2_800_000,
      liquidityUsd: 1_200_000,
      fdvUsd: 25_000_000,
      priceChange24h: 18,
      quoteLockRatio: 0.32,
      volumeSpikeRatio: 6.5,
      volumeAccelRatio: 3.2,
      daysSinceLaunch: 8,
      launchAt: "2026-08-20T20:59:46.000Z",
      longUrl: `https://app.long.xyz/tokens/${BONER_ADDRESS}`,
    },
  },
  {
    id: "boner-d10-pre-pump",
    label: "Pre-weekend squeeze setup",
    date: "2026-08-30",
    description: "Lock ≥45%, volume high — STRONG before NYSE weekend.",
    minLevel: "strong",
    input: {
      address: BONER_ADDRESS,
      symbol: "BONER",
      primaryPair: "BONER/HIMS",
      quoteSymbol: "HIMS",
      isStockPaired: true,
      volume24hUsd: 8_500_000,
      liquidityUsd: 2_100_000,
      fdvUsd: 42_000_000,
      priceChange24h: 35,
      quoteLockRatio: 0.48,
      volumeSpikeRatio: 7.2,
      volumeAccelRatio: 2.8,
      daysSinceLaunch: 10,
      launchAt: "2026-08-20T20:59:46.000Z",
      longUrl: `https://app.long.xyz/tokens/${BONER_ADDRESS}`,
    },
  },
  {
    id: "boner-d11-pump",
    label: "Weekend pump in progress",
    date: "2026-08-31",
    description: "Already pumping — should still be STRONG (confirmation, may be late for entry).",
    minLevel: "strong",
    input: {
      address: BONER_ADDRESS,
      symbol: "BONER",
      primaryPair: "BONER/HIMS",
      quoteSymbol: "HIMS",
      isStockPaired: true,
      volume24hUsd: 11_000_000,
      liquidityUsd: 2_400_000,
      fdvUsd: 50_000_000,
      priceChange24h: 52,
      quoteLockRatio: 0.55,
      volumeSpikeRatio: 8.1,
      daysSinceLaunch: 11,
      launchAt: "2026-08-20T20:59:46.000Z",
      longUrl: `https://app.long.xyz/tokens/${BONER_ADDRESS}`,
    },
  },
];
